### ISSUE TITLE
Allow per project config

### ISSUE THREAD

**Issue by nikolay** [devsisters/eclair#4]
Although there's an environment variable, it would be nice if the tool checks for the variable, then `./.ecl/config.rb`, and finally `~/.ecl/config.rb`.

**Comment by synthdnb** [comment]
I agree with there should be some way to switch config per use, but it should not be current-directory based since this is a ssh tool, and ssh is independent of current directory. I'm thinking about using passing parameter to eclair like `ecl projname`
