### ISSUE TITLE
aws multiple profile 사용 옵션 기능 요청

### ISSUE THREAD

**Issue by kangjoonsoo** [devsisters/eclair#5]
안녕하세요.
eclair를 오픈소스로 공개해주신 덕분에 잘 사용하고 있습니다.

한가지 기능을 요청드리고 싶은데요.
최근에 저희가 AWS를 Live와 Dev 용도로 계정을 분리해서 사용하면서 계속 설정을 변경해줘야 하는 불편이 생겼습니다.
```
$ ecl --profile live
```
그래서 위와 같이 옵션을 주는 경우, ~/.aws/config와 ~/.aws/credentials의 정보를 사용하면 어떨까요?

감사합니다.

**Comment by serialx** [comment]
`AWS_PROFILE=live ecl` 과 같은 형태로 사용 가능할 수 있습니다.  한 번 테스트해보시고 작동하면 알려주실 수 있나요?  감사합니다.

**Comment by kangjoonsoo** [comment]
알려주신 것처럼 환경변수를 넣었을 때, ~/.aws/credentials 정보를 불러와서 동작하네요.
하지만 ~/.aws/config의 정보가 사용되지 않아 .eclrc의 `config.aws_region = "ap-northeast-1"` 정보를 별도로 수정해줘야 하네요.
감사합니다.

**Comment by kgcrom** [comment]
config.aws_region= ... 줄을 주석 처리한 후
아래 처럼 환경변수로 설정하면 적용이 되네요
```
$> AWS_REGION=ap-northeast-1 AWS_PROFILE=live ecl
```

이런 좋은 project를 공개 해주셔서 감사합니다
